name: Build Ren'Py Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Setup Android SDK & NDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        ndk-version: 21.4.7075529
        build-tools-version: 30.0.3
    
    - name: Download Ren'Py SDK
      run: |
        cd ~
        wget -q https://www.renpy.org/dl/8.2.3/renpy-8.2.3-sdk.tar.bz2
        tar xjf renpy-8.2.3-sdk.tar.bz2
        echo "RENPY_PATH=$HOME/renpy-8.2.3-sdk" >> $GITHUB_ENV
    
    - name: Setup Android config files
      continue-on-error: true
      run: |
        python3 setup_android_files.py || true
    
    - name: Generate dummy assets (optional)
      continue-on-error: true
      run: |
        python3 generate_dummies.py 2>/dev/null || true
    
    - name: Configure Android build
      run: |
        mkdir -p ~/.renpy
        cat > ~/.renpy/android.json << 'EOF'
        {
          "package": "com.example.jensdilamma",
          "name": "Jens Dilemma",
          "version": "1.0",
          "orientation": "landscape",
          "icon_filename": "game/gui/window_icon.png",
          "presplash_filename": "game/gui/presplash.png",
          "android_api": "30",
          "android_ndk": "21.4.7075529",
          "android_sdk": "30"
        }
        EOF
    
    - name: Build APK
      run: |
        cd ${{ github.workspace }}
        echo "=== Starting Android build ==="
        echo "RENPY_PATH: $RENPY_PATH"
        echo "Current dir: $(pwd)"
        ls -la
        
        echo -e "\n=== Installing SDK ==="
        python3 $RENPY_PATH/rapt.py installsdk 2>&1 | tail -20
        
        echo -e "\n=== Configuring build ==="
        python3 $RENPY_PATH/rapt.py configure 2>&1 | tail -20
        
        echo -e "\n=== Building APK (this may take a while) ==="
        python3 $RENPY_PATH/rapt.py build . release 2>&1
    
    - name: Check for APK
      if: always()
      run: |
        echo "=== Searching for APK files ==="
        find ${{ github.workspace }} -name "*.apk" -type f 2>/dev/null | head -20 || echo "No APK found"
        
        echo -e "\n=== Checking bin/ folder ==="
        ls -lah ${{ github.workspace }}/bin/ 2>/dev/null || echo "No bin/ folder"
        
        echo -e "\n=== Checking full structure ==="
        find ${{ github.workspace }} -maxdepth 3 -type d | head -30
    
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: JensDilemma-Android
        path: ${{ github.workspace }}/bin/*.apk
        if-no-files-found: warn
        retention-days: 30
